### ISSUE TITLE
how to add brick in refactored cli?

### ISSUE THREAD

**Issue by epaulson** [ektrah/rdf-toolkit#4]
I'm a little unclear how to get the static site generator to include new files. I checked out and built a current copy of the latest code, and ran 
`npx rdf make site` 
and then 
`npx rdf serve`

and saw the base - owl, rdfs, and rdf

Then, I downloaded a copy of Brick.ttl and put it in explorer/vocab, and from explorer/ I ran
`npx rdf add file "https://brickschema.org/schema/Brick#" vocab/Brick.ttl`

and then ran `npx rdf list files` and I got
```bash
npx rdf list files
  ╤
  ├╼ <http://www.w3.org/1999/02/22-rdf-syntax-ns> → vocab/rdf.ttl
  ├╼ <http://www.w3.org/2000/01/rdf-schema> → vocab/rdfs.ttl
  ├╼ <http://www.w3.org/2002/07/owl> → vocab/owl.ttl
  ╰╼ <https://brickschema.org/schema/Brick> → vocab/Brick.ttl
```
but when I restart the 'serve' and visit, I don't see any of the brick classes. I do see it listed under 'files' so I hope I was on the right track:
![image](https://user-images.githubusercontent.com/315267/233220445-8254f85c-368f-4ba0-8289-d06cecafba85.png)

but I think I'm missing a step.

**Comment by ektrah** [comment]
I tried to reproduce this by downloading the nightly build of Brick.ttl into the `explorer/vocab/` directory and running these steps:

```bat
cd explorer
npx rdf add file "https://brickschema.org/schema/Brick#" vocab/Brick.ttl
npx rdf make site
npx rdf serve
```

This generates about 2.36 GB of HTML files and all the Brick classes show up for me when browsing <http://localhost:8000/>.

If you were missing any of these steps, I don't think the file would show up under "Files".

Maybe a browser cache issue?

Which version (commit) of the tool, NodeJS version, and operating system are you using?

**Comment by epaulson** [comment]
No, I am an idiot. curl didn't follow the 302 when I downloaded Brick, so while I had a Brick.ttl in the directory, it was 0 bytes. (I checked it but I checked a Brick.ttl in the wrong directory) 

Sorry for the distraction, all works as expected.
